apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot2-dec13-2-app
  namespace: ai-rhdh
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/chatbot2-dec13-2/overlays/development
    repoURL: https://github.com/redhat-appstudio-mjf/chatbot2-dec13-2-gitops.git
    targetRevision: main
  destination:
    namespace: chatbot2-dec13-2
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: ai-rhdh
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
