apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: chatbot2-dec13-2
  janus-idp.io/tekton: chatbot2-dec13-2
  backstage.io/kubernetes-id: chatbot2-dec13-2
  backstage.io/kubernetes-namespace: chatbot2-dec13-2 
  app.kubernetes.io/part-of: chatbot2-dec13-2
resources: 
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
- rhoai/
