apiVersion: v1
kind: ConfigMap
metadata:
  name: chatbot2-dec13-2-model-config
data:
  MODEL_ENDPOINT: "http://modelserver-dec13-1-model-server.modelserver-dec13-1:8001"
  MODEL_NAME: "ibm-granite/granite-3.0-8b-instruct"